/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare function compile(cfg: CompileOption): CompileResult

export interface CompileOption {
  outputType: string
  tagNamePrefix: string
  src: Record<string, Uint8Array>
}

export interface CompileResult {
  importIndex: Buffer
  files: Record<string, CompileResultItem>
}

export interface CompileResultItem {
  content: Buffer
  warnings: Array<string>
}

export declare function compileSingle(cfg: CompileSingleOption): CompileResultItem

export interface CompileSingleOption {
  fileContent: Buffer
  fileName: string
  outputType: string
  tagNamePrefix: string
}

export declare function compileSingleSync(cfg: CompileSingleOption): CompileResultItem

export declare function compileSync(cfg: CompileOption): CompileResult
