/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export interface CompileOption {
  outputType: string
  tagNamePrefix: string
  src: Record<string, Uint8Array>
}
export interface CompileResultItem {
  content: Buffer
  warnings: Array<string>
}
export interface CompileResult {
  importIndex: Buffer
  files: Record<string, CompileResultItem>
}
function compileSync(cfg: CompileOption): CompileResult
function compile(cfg: CompileOption): Promise<CompileResult>
